server.port=8083
spring.application.name=booking-service
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/booking_db}

# Secret API Key required for direct service access
api.key.secret=SecretApiKey12345

# Swagger OpenAPI docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
