server.port=8085
spring.application.name=payment-service
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/payment_db}
api.key.secret=SecretApiKey12345

# Swagger OpenAPI docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
